meta:
  version: 1
  inputs:
  - path: /home/aeon/repos/autoware_sentinel/src/sentinel_bringup/launch/system.launch.xml
    sha256: d4b08c70d1b6b543445d917a6fe71c6a1c51db1c942dc1fce7c3a5f32fd48aa2
  - path: /home/aeon/repos/autoware_sentinel/src/sentinel_bringup/system.toml
    sha256: b1e94306afc28887aeab95ebeea713dcc2a746c5de220c9eee08c464bcd02f72
  resolver:
    tool: play_launch
    version: 0.8.2
structure:
  scopes:
    system.launch.xml:
      file: system.launch.xml
  nodes:
    /adapi/default_adapi:
      scope: system.launch.xml
      pkg: sentinel_default_adapi_node
      exec: default_adapi
      node_name: default_adapi
    /control/autoware_operation_mode_transition_manager:
      scope: system.launch.xml
      pkg: sentinel_operation_mode_node
      exec: operation_mode
      params:
        op_mode.acc_threshold: 1.5
        op_mode.allow_autonomous_in_stopped: 'True'
        op_mode.enable_engage_on_driving: 'False'
        op_mode.speed_lower_threshold: -10.0
        op_mode.speed_upper_threshold: 10.0
        op_mode.stable_check_duration: 0.1
        op_mode.stopped_velocity_threshold: 0.01
      node_name: autoware_operation_mode_transition_manager
    /control/autoware_shift_decider:
      scope: system.launch.xml
      pkg: sentinel_shift_decider_node
      exec: shift_decider
      params:
        shift_decider.park_on_goal: 'True'
      node_name: autoware_shift_decider
    /control/control_validator:
      scope: system.launch.xml
      pkg: sentinel_control_validator_node
      exec: control_validator
      params:
        control_validator.acc_error_offset: 0.8
        control_validator.acc_error_scale: 0.2
        control_validator.acc_lpf_gain: 0.97
        control_validator.jerk_lpf_gain: 0.8
        control_validator.lateral_jerk_threshold: 10.0
        control_validator.over_velocity_offset: 2.0
        control_validator.over_velocity_ratio: 0.2
        control_validator.rolling_back_velocity: 0.5
        control_validator.vel_lpf_gain: 0.9
      node_name: control_validator
    /control/trajectory_follower/controller_node_exe:
      scope: system.launch.xml
      pkg: sentinel_controller_node
      exec: controller_node_exe
      params:
        controller.ctrl_period: 0.033
        controller.ego_nearest_dist_threshold: 3.0
        controller.ego_nearest_yaw_threshold: 1.57
        mpc.input_delay: 0.0
        mpc.prediction_dt: 0.1
        mpc.prediction_horizon: 50
        mpc.steer_rate_lim: 1.7321
        mpc.steer_tau: 0.27
        mpc.steering_lpf_gain: 0.8
        pid.delay_compensation_time: 0.17
        pid.emergency_acc: -5.0
        pid.kd: 0.0
        pid.ki: 0.1
        pid.kp: 1.0
        pid.max_acc: 3.0
        pid.max_jerk: 2.0
        pid.min_acc: -5.0
        pid.min_jerk: -5.0
        pid.stopped_acc: -3.4
        vehicle_info.front_overhang: 1.0
        vehicle_info.left_overhang: 0.128
        vehicle_info.max_steer_angle: 0.7
        vehicle_info.rear_overhang: 1.1
        vehicle_info.right_overhang: 0.128
        vehicle_info.vehicle_height: 2.5
        vehicle_info.wheel_base: 2.79
        vehicle_info.wheel_radius: 0.383
        vehicle_info.wheel_tread: 1.64
        vehicle_info.wheel_width: 0.235
      node_name: controller_node_exe
    /control/vehicle_cmd_gate:
      scope: system.launch.xml
      pkg: sentinel_vehicle_cmd_gate_node
      exec: vehicle_cmd_gate
      params:
        vehicle_cmd_gate.emergency_accel: -2.4
        vehicle_cmd_gate.heartbeat_timeout_ms: 5000
        vehicle_cmd_gate.stop_hold_accel: -1.5
        vehicle_cmd_gate.vel_lim: 25.0
      node_name: vehicle_cmd_gate
    /sensing/vehicle_velocity_converter:
      scope: system.launch.xml
      pkg: sentinel_velocity_converter_node
      exec: velocity_converter
      params:
        stop_filter.vx_threshold: 0.1
        stop_filter.wz_threshold: 0.02
        twist2accel.accel_lowpass_gain: 0.9
        velocity_converter.speed_scale_factor: 1.0
        velocity_converter.stddev_vx: 0.2
        velocity_converter.stddev_wz: 0.1
      node_name: vehicle_velocity_converter
    /system/mrm_comfortable_stop_operator:
      scope: system.launch.xml
      pkg: sentinel_mrm_comfortable_stop_node
      exec: comfortable_stop_operator
      params:
        mrm_comfortable_stop.min_acceleration: -1.0
        mrm_comfortable_stop.min_jerk: -0.3
      node_name: mrm_comfortable_stop_operator
    /system/mrm_emergency_stop_operator:
      scope: system.launch.xml
      pkg: sentinel_mrm_emergency_stop_node
      exec: emergency_stop_operator
      params:
        mrm_emergency_stop.target_acceleration: -2.5
        mrm_emergency_stop.target_jerk: -1.5
      node_name: mrm_emergency_stop_operator
    /system/mrm_handler:
      scope: system.launch.xml
      pkg: sentinel_mrm_handler_node
      exec: mrm_handler
      params:
        heartbeat.timeout_ms: 60000
        mrm_handler.stopped_velocity_threshold: 0.001
      node_name: mrm_handler
    /system/mrm_pull_over_manager:
      scope: system.launch.xml
      pkg: sentinel_mrm_pull_over_node
      exec: pull_over_manager
      node_name: mrm_pull_over_manager
    /system/system_monitor:
      scope: system.launch.xml
      pkg: sentinel_system_monitor_node
      exec: system_monitor
      node_name: system_monitor
execution:
  deploy:
    /adapi/default_adapi:
      target: mcu:mps2-an385-freertos
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: freertos
        kind: embedded
        target: thumbv7m-none-eabi
    /control/autoware_operation_mode_transition_manager:
      target: mcu:mps2-an385-freertos
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: freertos
        kind: embedded
        target: thumbv7m-none-eabi
    /control/autoware_shift_decider:
      target: mcu:mps2-an385-freertos
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: freertos
        kind: embedded
        target: thumbv7m-none-eabi
    /control/control_validator:
      target: mcu:mps2-an385-freertos
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: freertos
        kind: embedded
        target: thumbv7m-none-eabi
    /control/trajectory_follower/controller_node_exe:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /control/vehicle_cmd_gate:
      target: mcu:mps2-an385-freertos
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: freertos
        kind: embedded
        target: thumbv7m-none-eabi
    /sensing/vehicle_velocity_converter:
      target: mcu:mps2-an385-freertos
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: freertos
        kind: embedded
        target: thumbv7m-none-eabi
    /system/mrm_comfortable_stop_operator:
      target: mcu:mps2-an385-freertos
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: freertos
        kind: embedded
        target: thumbv7m-none-eabi
    /system/mrm_emergency_stop_operator:
      target: mcu:mps2-an385-freertos
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: freertos
        kind: embedded
        target: thumbv7m-none-eabi
    /system/mrm_handler:
      target: mcu:mps2-an385-freertos
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: freertos
        kind: embedded
        target: thumbv7m-none-eabi
    /system/mrm_pull_over_manager:
      target: mcu:mps2-an385-freertos
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: freertos
        kind: embedded
        target: thumbv7m-none-eabi
    /system/system_monitor:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
