<?xml version="1.0"?>
<package format="3">
  <name>sentinel_shift_decider_node</name>
  <version>0.1.0</version>
  <description>Sentinel declarative wrapper for /control/autoware_shift_decider.</description>
  <maintainer email="jerry73204@gmail.com">Autoware Sentinel contributors</maintainer>
  <license>Apache-2.0</license>
  <depend>autoware_system_msgs</depend>
  <depend>autoware_vehicle_msgs</depend>

  <export>
    <build_type>ament_cargo</build_type>
  </export>
</package>
